# Generated by Django 5.0.6 on 2025-01-20 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet_room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet_room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
