# Generated by Django 5.0.6 on 2025-01-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tweet', '0004_customeduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomedUser',
            new_name='CustomUser',
        ),
    ]
