# Generated by Django 5.0.6 on 2025-01-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_rename_customeduser_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
